name 'rancher'
maintainer 'Paul Czarkowski'
maintainer_email 'username.taken@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures rancher'
long_description 'Installs/Configures rancher'
version '0.1.0'

depends 'docker', '~> 0.37.0'
depends 'chef-sugar', '~> 3.1.0'
